# Generated by Django 5.0.6 on 2024-05-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivarity',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
